---
- hosts: dev
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      shell: "sudo docker pull {{ default_container_image }}:{{DOCKER_TAG}}"

#    - name: Create default containers
#      shell: "sudo docker run -d -p 8080:8080 --name {{ default_container_name }} -v '/var/run/docker.sock:/var/run/docker.sock' {{ default_container_image }}:{{DOCKER_TAG}}"
    # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}:{{DOCKER_TAG}}"
        state: present
        published_ports:
          - 172.180.0.22:8080:8080
