---
- hosts: dev
  become: True
  tasks:
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: Start the container
      docker_container:
        name: hariapp
        image: "jmlhmd/dockerfile:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
